site_name: SOFTware
nav:
  - Home: index.md
  - SOFTware-Sync : sync.md
  - SOFTware-Viz : viz.md
  - SOFTware-Check : check.md
  - SOFTware-Hub : hub.md
  - About: about.md
theme:
  name: readthedocs
  locale: fr
  logo: /img/SOFTWARE_all.png